tiles = {
    0: {
        "type": "Floor",
        "name": "Stone Floor",
        "walkable": True,
        "qty": "",
        "strikes": "",
        "symbol": "⬜",
        "spawn_probablity": 100,
    },
    1: {
        "type": "Wall",
        "name": "Brick Wall",
        "walkable": False,
        "qty": "",
        "strikes": "",
        "symbol": "🧱",
        "spawn_probablity": 10,
    },
    2: {
        "type": "Water",
        "name": "Shallow Water",
        "walkable": False,
        "qty": "",
        "strikes": "",
        "symbol": "🟦",
        "spawn_probablity": 25,
    },
    3: {
        "type": "Grass",
        "name": "Tall Grass",
        "walkable": True,
        "qty": "",
        "strikes": "",
        "symbol": "🟩",
        "spawn_probablity": 80,
    },
    4: {
        "type": "Lava",
        "name": "Hot Lava",
        "walkable": False,
        "qty": "",
        "strikes": 50,
        "symbol": "🟥",
        "spawn_probablity": 5,
    },
    5: {
        "type": "Door",
        "name": "Wooden Door",
        "walkable": True,
        "qty": "",
        "strikes": 5,
        "symbol": "🚪",
        "spawn_probablity": 20,
    },
    6: {
        "type": "Chest",
        "name": "Treasure Chest",
        "walkable": False,
        "qty": 1,
        "strikes": 10,
        "symbol": "📦",
        "spawn_probablity": 8,
    },
    7: {
        "type": "Trap",
        "name": "Spike Trap",
        "walkable": True,
        "qty": "",
        "strikes": 25,
        "symbol": "⚠️",
        "spawn_probablity": 12,
    },
    8: {
        "type": "Tree",
        "name": "Oak Tree",
        "walkable": False,
        "qty": "",
        "strikes": "",
        "symbol": "🌳",
        "spawn_probablity": 30,
    },
    9: {
        "type": "Bridge",
        "name": "Wooden Bridge",
        "walkable": True,
        "qty": "",
        "strikes": "",
        "symbol": "🟫",
        "spawn_probablity": 15,
    },
    10: {
        "type": "Sand",
        "name": "Desert Sand",
        "walkable": True,
        "qty": "",
        "strikes": "",
        "symbol": "🟨",
        "spawn_probablity": 40,
    },
    11: {
        "type": "Portal",
        "name": "Magic Portal",
        "walkable": True,
        "qty": "",
        "strikes": "",
        "symbol": "🌀",
        "spawn_probablity": 3,
    },
    12: {
        "type": "Enemy",
        "name": "Goblin Spawn",
        "walkable": False,
        "qty": 1,
        "strikes": 15,
        "symbol": "👹",
        "spawn_probablity": 7,
    },
}
